### ISSUE TITLE
Missing emission lines in galaxy templates

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#111] opened 2018-04-10 05:42 UTC
Looking at the residuals of galaxy in DR7, DR12 and DR14 we can see that some lines are missing in the redrock galaxy templates, created from desisim galaxies. The following plots show these different lines for the three data sets. The last plot shows a line observed in the templates but not observed in the data.

The wavelength are by eye: 9533, 9071, 7137, 6301, 2496 A

DR7 
![dr7_galaxy_missing_lines](https://user-images.githubusercontent.com/3166436/38537907-289eb760-3c46-11e8-8b9e-d11948fac6f7.png)

BOSS 
![boss_galaxy_missing_lines](https://user-images.githubusercontent.com/3166436/38537909-28be1664-3c46-11e8-9e75-1e658e5b8b2a.png)

DR14
![eboss_dr14_galaxy_missing_lines](https://user-images.githubusercontent.com/3166436/38537906-28737302-3c46-11e8-86f0-de1822547fa0.png)

![eboss_dr14_galaxy_missing_lines_otherline3](https://user-images.githubusercontent.com/3166436/38538115-29f8eb8e-3c47-11e8-9fa7-1cb075d7cb84.png)
![eboss_dr14_galaxy_missing_lines_otherline2](https://user-images.githubusercontent.com/3166436/38538116-2a1a9770-3c47-11e8-8a61-a7f9f11eaf8c.png)
![eboss_dr14_galaxy_missing_lines_otherline1](https://user-images.githubusercontent.com/3166436/38538118-2a378d9e-3c47-11e8-8d8a-0495485e1fc8.png)

**Comment by londumas** [comment] 2018-04-10 17:01
Here are some high SNR examples:
```
7275 57093 304
7275 57093 810
```

**Comment by ngbusca** [comment] 2018-04-11 13:28
@moustakas would it make sense to build them from eBOSS data? What are those empirical models like? PCA or something else?

**Comment by moustakas** [comment] 2018-04-11 13:51
I think eBOSS would be a great.  I hadn't previously pursued using eBOSS spectra because the requisite data weren't public, but I'm sure the public samples are large enough now.  

I'm not a fan of PCA because stars are never negative.  Non-negative matrix factorization or archetype methods (see, e.g., [this notebook](https://github.com/desihub/desisim/blob/master/doc/nb/bgs-archetypes.ipynb)) would be preferable.   

The approach I've used for the current set of (galaxy) templates is to model the available data (spectra + broadband photometry, e.g., from DEEP2 for ELGs) using stellar population synthesis models for the continuum + Gaussian emission-line fitting. This model-based but empirically constrained approach yields spectral templates with the necessary spectral resolution and wavelength coverage for DESI.  Archetypes or basis spectra can then be generated from this empirically constrained parent template set, as in redrock.

But there are many other subtle issues to consider, like differences in the wavelengths of the near-UV absorption lines due to outflows / winds vs the nebular emission lines, which will show up as systematic redshift errors.  However, I'm sure many of these issues have been worked on in eBOSS.

My point is that I think we need to gradually move away from the templates I built which we've been using the past N years and get ready to use "real", DESI-like data.

**Comment by londumas** [comment] 2018-04-13 16:59
@moustakas, do you need only the wavelength or also the distribution of the strength of these lines?

I agree that at least we have to compare the templates with desi-like data (=eBOSS).
That is why I have looked at the residuals. If they had been flat enough, we could simply continue with the current templates. Unfortunately, we are loosing sensitivity currently because some lines are missing, or added or with different distribution of strength. But it is already very good.

**Comment by moustakas** [comment] 2018-04-16 03:34
At minimum the wavelengths of the lines.  In principle we can tune the relative strengths but I'd be surprised if this affected the redshift results in a measurable way.  But I've been known to be wrong...

**Comment by moustakas** [comment] 2018-04-16 19:25
Either, but vacuum is probably easiest.

**Comment by londumas** [comment] 2018-04-18 00:34
In the same rest frame as the desisim galaxies:
Missing:
[SIII]9532 -> 9533
[SIII]9069 -> 9070
[ArIII]7138 -> 7137.7
[OI]6302 -> 6302.05

Should not exist:
2496

**Comment by moustakas** [comment] 2018-06-01 13:22
(This issue should really be posted as a `desisim` issue.)

I never quite finished documenting how I incorporate emission lines into the ELG AND BGS templates, but here are some notes:
* All the line-strengths are relative to H-beta.  The hydrogen and helium recombination lines (assuming an helium-to-hydrogen abundance ratio of 0.0897) are built assuming case B and listed [here](https://github.com/desihub/desisim/blob/master/py/desisim/data/recombination_lines.ecsv).  One important piece of physics missing from these emission-line ratios is intrinsic dust attenuation, but there are reasons why I have not yet included it.

* The somewhat limited set of forbidden lines included in the model are listed [here](https://github.com/desihub/desisim/blob/master/py/desisim/data/forbidden_lines.ecsv).  The line-ratios of the doublets (e.g., [NII] 6584/6548) are set by atomic physics, while the line-ratios relative to H-beta (e.g., [NII]/H-beta) are drawn from Gaussian mixture models fitted to data from various surveys (see [this notebook](https://github.com/desihub/desisim/blob/master/doc/nb/calib-emline.ipynb)).  I have confirmed that the forbidden emission-line sequences are broadly consistent with observations of galaxies to z~2, so they should be good for early DESI observations.

* In order to add additional lines like the [SIII] 9069,9532 doublet (which depends on electron temperature), [ArIII] 7138, [OI] 6302 (which is sensitive to shocks), and other lines (like [NeIII] 3869), we just need to choose line-ratios, add them to `forbidden_lines.ecsv` file, and then add a few lines of code to `desisim.templates.EMSpectrum` (see [here](https://github.com/desihub/desisim/blob/master/py/desisim/templates.py#L19)).  

In case we want to add even more forbidden lines (about which I welcome your thoughts, @londumas), we could use [galev_emlines.txt](https://github.com/desihub/redrock/files/2062806/galev_emlines.txt), which I obtained from R. Kotulla a few years ago, although some/many/most of the line-ratios are really only suitable for low-mass, low-metallicity starbursts.

Alternatively, `FSPS` also has a [reasonably complete line-list](https://github.com/cconroy20/fsps/blob/master/data/emlines_info.dat).

Let me know how you'd like to proceed.

**Comment by londumas** [comment] 2018-09-25 16:05
This is fixed thanks to @moustakas: https://github.com/desihub/desisim/pull/426 and https://github.com/desihub/desisim/pull/424
The new templates are in PR in https://github.com/desihub/redrock-archetypes/pull/7 and in https://github.com/desihub/redrock-templates/pull/8
Testing on some DR14 ELG+LRG truth table plate, I get:
```
### Master
                   ntarg   good  fail  miss  lost
BAD                   65   0.00 43.08  0.00 56.92
GALAXY              1458  97.19  0.34  0.69  1.78
QSO                   61  95.08  3.28  1.64  0.00
STAR                  66  100.00  0.00  0.00  0.00
```

```
### new templates + new archetypes
                   ntarg   good  fail  miss  lost
BAD                   65   0.00 38.46  0.00 61.54
GALAXY              1458  97.39  0.34  0.62  1.65
QSO                   61  95.08  3.28  1.64  0.00
STAR                  66  100.00  0.00  0.00  0.00
```

Here is what we use to have and what we get for one spectrum:

![spec_old_model](https://user-images.githubusercontent.com/3166436/46026727-556ccd80-c0a9-11e8-8192-29e0fc8d260c.png)

![spec_new_model](https://user-images.githubusercontent.com/3166436/46026726-556ccd80-c0a9-11e8-8f07-826adc1d9e01.png)

**Comment by sbailey** [comment] 2018-09-25 17:48
Thanks for the multi-repo fix.  Closing this ticket.

**Closed by sbailey** 2018-09-25 17:48 UTC
Labels: enhancement
